image: gitpod/workspace-full

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
              - cmake --config Debug --target HelloWorld -S . -B build
              - cmake --build build -- -j 18
              - ./build/HelloWorld
