image: gitpod/workspace-full

pipelines:
  default:
    - step:
        name: Build
        script:
          - gprbuild -P hello.gpr
        artifacts:
          - build/hello
    - step:
        name : Run
        script:
          - build/hello
