image: gitpod/workspace-full

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
              - echo $PWD
              - ls
              - cmake --build $PWD/build --config Debug --target HelloWorld -- -j 18
