image: gitpod/workspace-full

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
              - pwd
              - cmake --build /workspace/helloworld_in_c/build --config Debug --target HelloWorld -- -j 18
