image: gitpod/workspace-full

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            script:
              - cmake --config Debug --target HelloWorld -S . -B build
              - cmake --build build -- -j
        - step:
            name : Run
            script:
              - ./build/HelloWorld
